function props2copy = props2copy() % unfinished property getter helper. too lazy to complete...

% % gets the list of axis properties one might actually want to copy
% props2copy = {...
%     'ALim',...
%     'ALimMode',...
%     'AlphaScale',...
%     'Alphamap',...
%     'AmbientLightColor',...
%     'Box',...
%     'BoxStyle',...
%     'CLim',...
%     'CLimMode',...
%     'CameraPosition',...
%     'CameraPositionMode',...
%     'CameraTarget',...
%     'CameraTargetMode',...
%     'CameraUpVector',...
%     'CameraUpVectorMode',...
%     'CameraViewAngle',...
%     'CameraViewAngleMode',...
%     'Children',...
%     'Clipping',...
%     'ClippingStyle',...
%     'Color',...
%     'ColorOrder',...
%     'ColorOrderIndex',...
%     'ColorScale',...
%     'Colormap',...
%     'FontAngle',...
%     'FontName',...
%     'FontSmoothing',...
%     'FontWeight',...
%     'GridAlpha',...
%     'GridAlphaMode',...
%     'GridColor',...
%     'GridColorMode',...
%     'GridLineStyle',...
%     'Legend',...
%     'LineStyleOrder',...
%     'LineStyleOrderIndex',...
%     'LineWidth',...
%     'MinorGridAlpha',...
%     'MinorGridAlphaMode',...
%     'MinorGridColor',...
%     'MinorGridColorMode',...
%     'MinorGridLineStyle',...
%     'Projection',...
%     'SortMethod',...
%     'TickDir',...
%     'TickDirMode',...
%     'TickLabelInterpreter',...
%     'TickLength',...
%     'Title',...
%     'TitleFontSizeMultiplier',...
%     'TitleFontWeight',...
%     'Toolbar',...
%     'Type',...
%     'UserData',...
%     'View',...
%     'XAxis',...
%     'XAxisLocation',...
%     'XColor',...
%     'XColorMode',...
%     'XDir',...
%     'XGrid',...
%     'XLabel',...
%     'XLim',...
%     'XLimMode',...
%     'XMinorGrid',...
%     'XMinorTick',...
%     'XScale'...
%     'XTick': [-1.5000 -1 -0.5000 0 0.5000 1 1.5000]
%     XTickLabel: {7×1 cell}
%     XTickLabelMode: 'auto'
%     XTickLabelRotation: 0
%     XTickMode: 'auto'
%     YAxis: [1×1 NumericRuler]
%     YAxisLocation: 'left'
%     YColor: [0.1500 0.1500 0.1500]
%     YColorMode: 'auto'
%     YDir: 'normal'
%     YGrid: 'off'
%     YLabel: [1×1 Text]
%     YLim: [-2.5000 1.5000]
%     YLimMode: 'auto'
%     YMinorGrid: 'off'
%     YMinorTick: 'off'
%     YScale: 'linear'
%     YTick: [-2.5000 -2 -1.5000 -1 -0.5000 0 0.5000 1 1.5000]
%     YTickLabel: {9×1 cell}
%     YTickLabelMode: 'auto'
%     YTickLabelRotation: 0
%     YTickMode: 'auto'
%     ZAxis: [1×1 NumericRuler]
%     ZColor: [0.1500 0.1500 0.1500]
%     ZColorMode: 'auto'
%     ZDir: 'normal'
%     ZGrid: 'off'
%     ZLabel: [1×1 Text]
%     ZLim: [-1 1]
%     ZLimMode: 'auto'
%     ZMinorGrid: 'off'
%     ZMinorTick: 'off'
%     ZScale: 'linear'
%     ZTick: [-1 0 1]
%     ZTickLabel: ''
%     ZTickLabelMode: 'auto'
%     ZTickLabelRotation: 0
%     ZTickMode: 'auto'